import { StyleSheet } from 'react-native';

export const adminModerationStyles = StyleSheet.create({
	screen: { flex: 1, backgroundColor: '#f3f4f6' },
	content: { flex: 1 },
	filtersWrap: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 8, gap: 10 },
	searchContainer: {
		height: 44,
		borderRadius: 12,
		paddingHorizontal: 12,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#d1d5db',
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	searchInput: { flex: 1, fontSize: 14, color: '#111827' },
	chipRow: { flexDirection: 'row', gap: 8 },
	chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#e5e7eb' },
	chipActive: { backgroundColor: '#0f172a' },
	chipText: { fontSize: 11, fontWeight: '800', color: '#475569' },
	chipTextActive: { color: '#fefce8' },
	metaText: { fontSize: 12, color: '#64748b' },
	listContent: { padding: 12, paddingTop: 2, gap: 10, paddingBottom: 16 },
	card: {
		backgroundColor: '#ffffff',
		borderRadius: 14,
		padding: 12,
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
	title: { fontSize: 13, fontWeight: '900', color: '#111827', flex: 1 },
	badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, borderWidth: 1 },
	badgeText: { fontSize: 9, fontWeight: '900' },
	metaTextRow: { marginTop: 5, fontSize: 11, color: '#64748b' },
	commentText: { marginTop: 8, fontSize: 12, lineHeight: 17, color: '#334155' },
	reasonChip: { marginTop: 8, alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fdba74' },
	reasonText: { fontSize: 10, fontWeight: '800', color: '#9a3412' },
	actionsRow: { marginTop: 10, flexDirection: 'row', gap: 8 },
	actionButton: { flex: 1, paddingVertical: 9, borderRadius: 10, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
	actionButtonApprove: { backgroundColor: 'rgba(13, 77, 77, 0.12)' },
	actionButtonReject: { backgroundColor: 'rgba(125, 31, 62, 0.12)' },
	actionText: { fontSize: 11, fontWeight: '800' },
	feedbackWrap: { marginTop: 36, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
	feedbackText: { marginTop: 8, fontSize: 13, color: '#475569', textAlign: 'center' },
	errorText: { fontSize: 13, fontWeight: '800', color: '#9f1239', textAlign: 'center' },
});