import { StyleSheet } from 'react-native';

export const adminAchievementsStyles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: '#f3f4f6',
	},
	content: {
		flex: 1,
	},
	contentInner: {
		paddingHorizontal: 12,
		paddingTop: 10,
		paddingBottom: 18,
		gap: 12,
	},
	card: {
		backgroundColor: '#ffffff',
		borderRadius: 16,
		padding: 14,
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	cardHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
	},
	cardTitle: {
		fontSize: 16,
		fontWeight: '900',
		color: '#111827',
	},
	cardSubtitle: {
		marginTop: 4,
		fontSize: 12,
		color: '#64748b',
	},
	badge: {
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: 'rgba(146, 64, 14, 0.12)',
	},
	badgeText: {
		fontSize: 12,
		fontWeight: '800',
		color: '#92400e',
	},
	searchContainer: {
		height: 44,
		borderRadius: 12,
		paddingHorizontal: 12,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#d1d5db',
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	searchInput: {
		flex: 1,
		fontSize: 14,
		color: '#111827',
	},
	filterGroup: {
		marginTop: 12,
	},
	filterLabel: {
		marginBottom: 8,
		fontSize: 11,
		fontWeight: '800',
		color: '#334155',
	},
	filterRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	filterChip: {
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#dbe4ee',
	},
	filterChipActive: {
		backgroundColor: 'rgba(15, 118, 110, 0.12)',
		borderColor: 'rgba(15, 118, 110, 0.25)',
	},
	filterChipText: {
		fontSize: 11,
		fontWeight: '800',
		color: '#475569',
	},
	filterChipTextActive: {
		color: '#0f766e',
	},
	listCard: {
		backgroundColor: '#ffffff',
		borderRadius: 16,
		padding: 12,
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	sectionTitle: {
		fontSize: 15,
		fontWeight: '900',
		color: '#111827',
	},
	sectionSubtitle: {
		marginTop: 4,
		fontSize: 12,
		color: '#64748b',
	},
	achievementCard: {
		marginTop: 12,
		borderRadius: 14,
		padding: 12,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#e5e7eb',
	},
	achievementHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: 10,
	},
	achievementName: {
		fontSize: 14,
		fontWeight: '900',
		color: '#111827',
		flex: 1,
	},
	achievementDescription: {
		marginTop: 6,
		fontSize: 12,
		lineHeight: 18,
		color: '#475569',
	},
	chipRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginTop: 10,
	},
	chip: {
		paddingHorizontal: 8,
		paddingVertical: 5,
		borderRadius: 999,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
	},
	chipText: {
		fontSize: 10,
		fontWeight: '800',
		color: '#475569',
	},
	chipActive: {
		backgroundColor: 'rgba(15, 118, 110, 0.12)',
		borderColor: 'rgba(15, 118, 110, 0.25)',
	},
	chipTextActive: {
		color: '#0f766e',
	},
	formCard: {
		backgroundColor: '#ffffff',
		borderRadius: 16,
		padding: 14,
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	fieldLabel: {
		marginBottom: 6,
		fontSize: 11,
		fontWeight: '800',
		color: '#334155',
	},
	fieldInput: {
		minHeight: 44,
		borderRadius: 12,
		paddingHorizontal: 12,
		paddingVertical: 10,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#dbe4ee',
		fontSize: 14,
		color: '#111827',
	},
	fieldMultiline: {
		minHeight: 92,
		textAlignVertical: 'top',
	},
	fieldHint: {
		marginTop: 6,
		fontSize: 10,
		fontWeight: '600',
		color: '#64748b',
	},
	criteriaGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	criteriaChip: {
		flexGrow: 1,
		minWidth: '31%',
		borderRadius: 12,
		paddingHorizontal: 10,
		paddingVertical: 9,
		borderWidth: 1,
		borderColor: '#dbe4ee',
		backgroundColor: '#f8fafc',
	},
	criteriaChipActive: {
		backgroundColor: 'rgba(15, 118, 110, 0.12)',
		borderColor: 'rgba(15, 118, 110, 0.25)',
	},
	criteriaChipTitle: {
		fontSize: 11,
		fontWeight: '900',
		color: '#111827',
	},
	criteriaChipText: {
		marginTop: 4,
		fontSize: 10,
		color: '#64748b',
		lineHeight: 14,
	},
	toggleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 12,
		paddingHorizontal: 12,
		paddingVertical: 12,
		borderRadius: 12,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#dbe4ee',
	},
	toggleTextWrap: {
		flex: 1,
	},
	toggleTitle: {
		fontSize: 12,
		fontWeight: '800',
		color: '#111827',
	},
	toggleSubtitle: {
		marginTop: 3,
		fontSize: 10,
		color: '#64748b',
	},
	actionRow: {
		flexDirection: 'row',
		gap: 10,
		marginTop: 14,
	},
	primaryButton: {
		flex: 1,
		minHeight: 44,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#0f766e',
		flexDirection: 'row',
		gap: 8,
	},
	primaryButtonText: {
		fontSize: 12,
		fontWeight: '900',
		color: '#ffffff',
	},
	secondaryButton: {
		minHeight: 44,
		borderRadius: 12,
		paddingHorizontal: 14,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#dbe4ee',
	},
	secondaryButtonText: {
		fontSize: 12,
		fontWeight: '900',
		color: '#334155',
	},
	progressWrap: {
		marginTop: 12,
	},
	progressTrack: {
		height: 8,
		borderRadius: 999,
		backgroundColor: '#e5e7eb',
		overflow: 'hidden',
	},
	progressFill: {
		height: '100%',
		borderRadius: 999,
		backgroundColor: '#0f766e',
	},
	progressText: {
		marginTop: 6,
		fontSize: 10,
		fontWeight: '700',
		color: '#64748b',
	},
	emptyState: {
		paddingVertical: 18,
		alignItems: 'center',
		justifyContent: 'center',
	},
	emptyStateText: {
		fontSize: 13,
		color: '#64748b',
		textAlign: 'center',
	},
	feedbackWrap: {
		paddingVertical: 20,
		alignItems: 'center',
		justifyContent: 'center',
	},
	feedbackText: {
		marginTop: 8,
		fontSize: 13,
		color: '#475569',
		textAlign: 'center',
	},
});