import { StyleSheet } from 'react-native';

export const adminBookOfMonthStyles = StyleSheet.create({
	screen: { flex: 1, backgroundColor: '#f3f4f6' },
	content: { flex: 1 },
	contentInner: { padding: 12, paddingBottom: 16, gap: 12 },
	searchContainer: {
		height: 44,
		borderRadius: 12,
		paddingHorizontal: 12,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#d1d5db',
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	searchInput: { flex: 1, fontSize: 14, color: '#111827' },
	currentCard: {
		borderRadius: 16,
		padding: 12,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	currentTitle: { fontSize: 15, fontWeight: '900', color: '#111827' },
	currentSubtitle: { marginTop: 4, fontSize: 12, color: '#64748b' },
	bookCard: {
		borderRadius: 14,
		padding: 12,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
		flexDirection: 'row',
		gap: 10,
	},
	cover: { width: 64, height: 88, borderRadius: 10, backgroundColor: '#e5e7eb' },
	bookInfo: { flex: 1 },
	bookTitle: { fontSize: 13, fontWeight: '900', color: '#111827' },
	bookAuthor: { marginTop: 3, fontSize: 11, color: '#64748b', fontWeight: '700' },
	metaRow: { marginTop: 8, flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
	metaChip: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e5e7eb' },
	metaChipText: { fontSize: 10, fontWeight: '800', color: '#475569' },
	setButton: {
		marginTop: 10,
		minHeight: 38,
		borderRadius: 10,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(13, 77, 77, 0.12)',
		flexDirection: 'row',
		gap: 6,
	},
	setButtonActive: {
		backgroundColor: 'rgba(15, 118, 110, 0.18)',
		borderWidth: 1,
		borderColor: '#2dd4bf',
	},
	setButtonText: { color: '#0f766e', fontSize: 11, fontWeight: '800' },
	feedbackWrap: { marginTop: 36, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
	feedbackText: { marginTop: 8, fontSize: 13, color: '#475569', textAlign: 'center' },
});