import { StyleSheet } from 'react-native';

export const adminRegisterStyles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: '#f3f4f6',
	},
	content: {
		flex: 1,
	},
	contentInner: {
		padding: 12,
		paddingBottom: 18,
		gap: 12,
	},
	summaryCard: {
		borderRadius: 16,
		padding: 14,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	summaryTopRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
	},
	summaryTitle: {
		fontSize: 16,
		fontWeight: '900',
		color: '#111827',
	},
	summarySubtitle: {
		marginTop: 4,
		fontSize: 12,
		color: '#64748b',
	},
	summaryBadge: {
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: 'rgba(13, 77, 77, 0.12)',
	},
	summaryBadgeText: {
		fontSize: 12,
		fontWeight: '800',
		color: '#0f766e',
	},
	card: {
		borderRadius: 16,
		padding: 14,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
		shadowColor: '#000000',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	cardHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
		marginBottom: 12,
	},
	cardTitle: {
		fontSize: 15,
		fontWeight: '900',
		color: '#111827',
	},
	cardActionText: {
		fontSize: 11,
		fontWeight: '800',
		color: '#7D1F3E',
	},
	fieldLabel: {
		marginBottom: 6,
		fontSize: 11,
		fontWeight: '800',
		color: '#334155',
	},
	fieldHint: {
		marginTop: -2,
		marginBottom: 10,
		fontSize: 10,
		fontWeight: '600',
		color: '#64748b',
	},
	chapterHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
		marginTop: 4,
		marginBottom: 6,
	},
	addChapterButton: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		paddingHorizontal: 10,
		paddingVertical: 7,
		borderRadius: 999,
		backgroundColor: 'rgba(15, 118, 110, 0.08)',
		borderWidth: 1,
		borderColor: 'rgba(15, 118, 110, 0.18)',
	},
	addChapterButtonText: {
		fontSize: 11,
		fontWeight: '800',
		color: '#0f766e',
	},
	chaptersList: {
		gap: 10,
		marginBottom: 12,
	},
	chapterItem: {
		padding: 12,
		borderRadius: 12,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#e5e7eb',
	},
	chapterItemHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 10,
		marginBottom: 8,
	},
	chapterActionsGroup: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	chapterIndex: {
		fontSize: 12,
		fontWeight: '900',
		color: '#111827',
	},
	chapterActionButton: {
		width: 32,
		height: 32,
		borderRadius: 999,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(15, 118, 110, 0.08)',
		borderWidth: 1,
		borderColor: 'rgba(15, 118, 110, 0.15)',
	},
	chapterActionButtonDisabled: {
		opacity: 0.45,
	},
	removeChapterButton: {
		width: 32,
		height: 32,
		borderRadius: 999,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(159, 18, 57, 0.08)',
		borderWidth: 1,
		borderColor: 'rgba(159, 18, 57, 0.15)',
	},
	input: {
		minHeight: 44,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: '#d1d5db',
		backgroundColor: '#f8fafc',
		paddingHorizontal: 12,
		marginBottom: 12,
		color: '#111827',
	},
	inputReadonly: {
		justifyContent: 'center',
	},
	inputMultiline: {
		minHeight: 92,
		paddingTop: 12,
		textAlignVertical: 'top',
	},
	selectedGenreText: {
		fontSize: 14,
		color: '#111827',
		fontWeight: '700',
	},
	selectTrigger: {
		minHeight: 44,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: '#d1d5db',
		backgroundColor: '#f8fafc',
		paddingHorizontal: 12,
		marginBottom: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	selectTriggerText: {
		flex: 1,
		fontSize: 14,
		fontWeight: '700',
		color: '#111827',
	},
	selectTriggerPlaceholder: {
		color: '#94a3b8',
		fontWeight: '500',
	},
	selectList: {
		maxHeight: 220,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: '#d1d5db',
		backgroundColor: '#ffffff',
		marginBottom: 12,
		overflow: 'hidden',
	},
	selectOption: {
		minHeight: 44,
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#eef2f7',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	selectOptionText: {
		fontSize: 13,
		fontWeight: '700',
		color: '#334155',
	},
	selectOptionTextActive: {
		color: '#111827',
	},
	row: {
		flexDirection: 'row',
		gap: 10,
	},
	column: {
		flex: 1,
	},
	coverPreview: {
		width: 74,
		height: 98,
		borderRadius: 12,
		backgroundColor: '#e5e7eb',
	},
	coverPreviewWrap: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		marginBottom: 14,
	},
	coverPreviewText: {
		flex: 1,
		fontSize: 11,
		lineHeight: 16,
		color: '#64748b',
	},
	buttonRow: {
		flexDirection: 'row',
		gap: 10,
	},
	buttonTouch: {
		flex: 1,
	},
	primaryButton: {
		minHeight: 46,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
	},
	primaryButtonText: {
		color: '#fefce8',
		fontSize: 13,
		fontWeight: '900',
	},
	secondaryButton: {
		minHeight: 46,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 1,
		borderColor: '#cbd5e1',
		backgroundColor: '#f8fafc',
	},
	secondaryButtonText: {
		color: '#334155',
		fontSize: 13,
		fontWeight: '800',
	},
	helperText: {
		marginTop: 12,
		fontSize: 11,
		lineHeight: 16,
		color: '#64748b',
	},
	feedbackText: {
		fontSize: 12,
		color: '#64748b',
	},
	errorText: {
		fontSize: 12,
		fontWeight: '700',
		color: '#9f1239',
	},
	listGap: {
		gap: 12,
	},
	bookRow: {
		flexDirection: 'row',
		gap: 12,
		padding: 12,
		borderRadius: 14,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#e5e7eb',
	},
	bookInfo: {
		flex: 1,
	},
	bookTitle: {
		fontSize: 14,
		fontWeight: '900',
		color: '#111827',
	},
	bookAuthor: {
		marginTop: 2,
		fontSize: 12,
		fontWeight: '700',
		color: '#64748b',
	},
	metaRow: {
		marginTop: 8,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	metaChip: {
		paddingHorizontal: 8,
		paddingVertical: 5,
		borderRadius: 999,
		backgroundColor: '#ffffff',
		borderWidth: 1,
		borderColor: '#e5e7eb',
	},
	metaChipText: {
		fontSize: 10,
		fontWeight: '800',
		color: '#475569',
	},
	bookSynopsis: {
		marginTop: 8,
		fontSize: 11,
		lineHeight: 16,
		color: '#334155',
	},
	actionsRow: {
		marginTop: 10,
		flexDirection: 'row',
		gap: 8,
	},
	actionButton: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
	},
	actionButtonEdit: {
		backgroundColor: 'rgba(13, 77, 77, 0.12)',
	},
	actionButtonDelete: {
		backgroundColor: 'rgba(125, 31, 62, 0.12)',
	},
	actionButtonText: {
		fontSize: 11,
		fontWeight: '800',
	},
	emptyState: {
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 18,
		gap: 8,
	},
	emptyStateTitle: {
		fontSize: 13,
		fontWeight: '900',
		color: '#111827',
	},
	emptyStateText: {
		fontSize: 12,
		color: '#64748b',
		textAlign: 'center',
	},
});